name: Fithub2 Dev CI/CD

on:
  pull_request:
    types: [ closed ]
  workflow_dispatch: # (2).수동 실행도 가능하도록

jobs:
  build:
    runs-on: ubuntu-latest # (3).OS환경
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # (4).코드 check out

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17 # (5).자바 설치
          distribution: 'adopt'

      #      - name: Set Environment - Common Yml
      #        uses: microsoft/variable-substitution@v1
      #        with:
      #          files: ./src/main/resources/application.yml
      #        env:
      #          oauth.kakao.base-url: ${{ secrets.KAKAO_BASE_URL }}
      #          oauth.kakao.client-id: ${{ secrets.KAKAO_CLIENT }}
      #          oauth.kakao.client-secret: ${{ secrets.KAKAO_SECRET }}
      #          oauth.kakao.redirect-url: ${{ secrets.KAKAO_REDIRECT }}
      #          oauth.kakao.app-id: ${{ secrets.KAKAO_APP_ID }}
      #          oauth.kakao.admin-key: ${{ secrets.KAKAO_ADMIN_KEY }}
      #          jwt.secret: ${{ secrets.JWT_SECRET_KEY }}
      #          jwt.refresh: ${{ secrets.JWT_REFRESH_KEY }}
      #          cool-sms.api-key: ${{ secrets.COOL_SMS_API_KEY }}
      #          cool-sms.api-secret: ${{ secrets.COOL_SMS_API_SECRET }}
      #          cool-sms.from-number: ${{ secrets.COOL_SMS_FROM_NUMBER }}
      #          cool-sms.domain: ${{ secrets.COOL_SMS_DOMAIN }}
      #          aws.s3.bucket: ${{ secrets.AWS_BUCKET }}
      #          aws.s3.base-url: ${{ secrets.AWS_BASE_URL }}
      #          aws.s3.access-key: ${{ secrets.AWS_S3_ACCESS_KEY }}
      #          aws.s3.secret-key: ${{ secrets.AWS_S3_SECRET_KEY }}
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash # (6).권한 부여

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash # (7).build 시작

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00" # (8).build 시점의 시간확보

      - name: Show Current Time
        run: echo "CurrentTime=$"
        shell: bash # (9).확보한 시간 보여주기

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/application.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions-dev deploy/.ebextensions
          cp -r .platform deploy/.platform
          cd deploy && zip -r deploy.zip .

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACTION_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_ACTION_SECRET_ACCESS_KEY }}
          application_name: briefing-dev
          environment_name: Briefing-dev-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-1
          deployment_package: deploy/deploy.zip
          wait_for_environment_recovery: 60

